services:
  - type: web
    name: song-manager-api
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: PORT
        value: 3000